### ISSUE TITLE
Will there be sans version?

### ISSUE THREAD

**Issue by RuochenFu21** [notofonts/tangut#4]
**Is your feature request related to a problem? Please describe.**
There is Noto Serif Tangut, just wondering if there are plans for a sans serif version.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
I do acknowledge the effort and money required to make a font, and the lack of audience for this font as there is no one that speaks Tangut language as it was annihilated in year 1227. I am just curious if there is plan of making a sans serif version.

**Comment by simoncozens** [comment]
I'm afraid there are no plans, and as you mention it's not exactly something that's easy to prioritise. You might want to look at Babelstone's [Tangut Yinchuan](https://www.babelstone.co.uk/Fonts/Yinchuan.html) font as a sans-like alternative.
